### PR TITLE
Rebuilt Home Screen, removed redundant libraries.

### PR DESCRIPTION
**Pull request by nirbhaysinghnarang**
Rebuilt home screen. Removed FlutterFlow dependencies. Built out side nav-bar. Tested on iPhone SE and  iPhone 13 Pro Max for different viewports. Added 2 dependencies: sliding_up_panel (slide up panel) and velocity_x (row/col functionalities).

### Summary 
Redesigned HomeScreen without FlutterFlow dependencies. Implemented a slide-up panel, temperature box (for distance from location), added a side navigation bar. Used CupertinoIcons. Used dummy data. Tested on multiple viewports.

- [x] Home Screen

Remaining TODOs:

- [ ] Build out Leaderboard Screen.
- [ ] Build out Recently Visited Screen.

### Test Plan 

Test on Android devices, and physical if possible.

### CODE REVIEW

**Review by lobsterdude3 — COMMENTED** [review]
I can't seem to build it on android when I download it, not sure if it's my fault.

**Comment by nirbhaysinghnarang** [comment]
> I can't seem to build it on android when I download it, not sure if it's my fault.

I was using the Pixel emulator on VSCode, and it worked for me. What about iOS?

**Comment by lobsterdude3** [comment]
I was also trying the pixel emulator on VSCode. If it works for you it is probably something on my end then. Maybe someone else try it.

**Comment by nirbhaysinghnarang** [comment]
> I was also trying the pixel emulator on VSCode. If it works for you it is probably something on my end then. Maybe someone else try it.

Can you try running it on an iOS emulator if you have a Mac?

**Review by neketka — CHANGES_REQUESTED** [review]
[This link](https://stackoverflow.com/questions/70997381/flutter-error-no-named-parameter-with-the-name-displaylarge) might help solve the build problems. I think this has something to do with material's version in the pubspec.yaml being wrong.

**Review by neketka — APPROVED** [review]

**Pull request merged**
