### PR TITLE
Jxl9/challenges journeys

### PR DESCRIPTION
**Pull request by jasmineee-li**
### Edited UI for challenges & journeys 

This pull request updates the UI for journeys and challenges pages in accordance with the newly handed off designs

Remaining TODOs:

- [ ] connect challenges & journeys to backend

### CODE REVIEW

**Review by nit0107 — COMMENTED** [review]
Nice job, looks consistent with the hi-fi designs that were handed off!

**Comment by cathli66** [comment]
@nit0107, I saw you tested this branch too! Did you happen to test on an iOS device? I saw that a lot of iOS dependencies got updated during Jasmine's PR so wanted to make sure everything still runs fine on that end.

**Comment by cathli66** [comment]
Don't forget to update the pop up UI element after you press on a challenge/journey to the new designs on Figma also!

**Review by cathli66 — APPROVED** [review]
Everything is good on my end now! Thanks for addressing all the comments/reviews :)

**Pull request merged**
