### PR TITLE
add isAchievement and points as a field to reward

### PR DESCRIPTION
**Pull request by erichuang27**
### Summary 

Add isAchievement and points to reward field

- [x] Add isAchievement 
- [x] Add points
- [ ] add to primsa and admin frontend

Remaining TODOs:

- [ ] Points does not update in the backend, need help
- [ ] need to change in flutter

### Test Plan 

Need to test in postman

### Breaking Changes  

- Database schema change (anything that changes TypeORM entities)

### CODE REVIEW

**Comment by youssef-attia** [comment]
Very comprehensible changes towards adding these properties to rewards but I'm wondering why the RequestRewardDataDTO was removed? Do we no longer need it?

**Comment by nirbhaysinghnarang** [comment]
I think your changes are very easy to follow and variable names are informative!

**Comment by BrianLa0616** [comment]
Great changes! Everything looks good on the front end!

**Comment by BrianLa0616** [comment]
Great changes! Everything looks good on the front end! Not too sure why you can't add new changes into the backend.

**Comment by erichuang27** [comment]
> Very comprehensible changes towards adding these properties to rewards but I'm wondering why the RequestRewardDataDTO was removed? Do we no longer need it?

The same method was written twice in the function, So __ just removed it.

**Review by BrianLa0616 — DISMISSED** [review]

**Review by BrianLa0616 — APPROVED** [review]

**Pull request merged**
