### PR TITLE
Byl8/images backend

### PR DESCRIPTION
**Pull request by BrianLa0616**
### Summary 

This pull request is the first step towards implementing feature Foo

- [x] Added images in challenges, journeys, and gameplay page

Depends on #{number of PR}

### Test Plan 

image
image

### CODE REVIEW

**Review by cathli66 — CHANGES_REQUESTED** [review]
Images work on challenges journeys and gameplay! They also show up on the completed challenges page but don't look right. Could you also connect the images in the profile page too? Thanks :)
image
image

**Comment by cathli66** [comment]
Also, can you change this line in completed_challenges_page.dart? There's a bug with location type that does not let you see the page otherwise

image

**Comment by BrianLa0616** [comment]
> Images work on challenges journeys and gameplay! They also show up on the completed challenges page but don't look right. Could you also connect the images in the profile page too? Thanks :) image image

Done. I also changed the footer because it was weird for me. Hopefully it doesn't break for you.

**Review by cathli66 — APPROVED** [review]
Pictures are all working on my end! While testing, I also made some changes to the completed challenges UI to (hopefully) work well with any device.

**Pull request merged**
