### PR TITLE
add fade animations and border fade animations

### PR DESCRIPTION
**Pull request by erichuang27**
### Summary 

This pull request is the first step towards implementing feature Foo

- [x] Added animations for slow loading for rewards, challenges, and events
- [x] Added fade for the green borders

Remaining TODOs:

- [ ] Need to test everything

### Test Plan 

My docker broke for some reason so it hasn't been really tested, also hard to test in the emulator, need it to test on mobile and also need the fade for the green borders tested also.

### CODE REVIEW

**Review by neketka — CHANGES_REQUESTED** [review]
Something weird is going on in the event page 
image

**Review by nirbhaysinghnarang — CHANGES_REQUESTED** [review]
Simulator Screen Shot - iPhone 12 - 2022-05-01 at 16 18 13
Looks like the alignment of the border on the events page is incorrect. Besides this, I was unable to test on a physical device but tested on the emulator.

**Comment by erichuang27** [comment]
Should be fixed @neketka @nirbhaysinghnarang and force unwrapping has been removed

**Review by neketka — APPROVED** [review]
I fixed some fading issues, but LGTM.

**Review by nirbhaysinghnarang — APPROVED** [review]

**Pull request merged**
