### PR TITLE
Added requestGroupData in GroupGateway and getGroupForUser in GroupService

### PR DESCRIPTION
**Pull request by cathli66**
### Summary 

This pull request implements part of GroupGateway.

- [x] implemented requestGroupData
- [x] implemented getGroupForUser

Remaining TODOs:

- [ ] implement joinGroup
- [ ] implement leaveGroup

### CODE REVIEW

**Review by youssef-attia — COMMENTED** [review]
Everything you've added makes sense to me. I like that you made a method in Group Service to return the group info. I'll probably have to update my method so that I'm using that. I was curious whether it was relevant for when you're setting the curChallengeId on line 49 if it matters that getCurrentEventTrackerForUser might fail? I was told it would be better to put those kinds of issues in try catch blocks just in case but is there something in your code that makes this not necessary? Thanks

**Comment by neketka** [comment]
>I was curious whether it was relevant for when you're setting the curChallengeId on line 49 if it matters that getCurrentEventTrackerForUser might fail? 

Assuming that both joinGroup and setCurrentEvent preserve the invariant that a user has an event tracker for every event they've been in, this shouldn't ever fail.

**Review by neketka — CHANGES_REQUESTED** [review]
Make sure to fix the event id and code style issue, then it should be good to go.

**Review by neketka — APPROVED** [review]
LGTM

**Pull request merged**
